on:
  push:
    branches: ["main"]

name: Publish the page

env:
  HUGO_IMAGE: hugomods/hugo:exts-0.139.5

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build with Hugo
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            ${{ env.HUGO_IMAGE }} \
            --minify

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Configure remote
        run: rclone config create remote sftp

      - name: Copy the files
        run: |
          rclone copy public remote:/home/vbmntcj/www/ \
            --sftp-pass=$(rclone obscure "${{ secrets.SFTP_PASS }}") \
            --sftp-host="${{ secrets.SFTP_HOST }}" \
            --sftp-user="${{ secrets.SFTP_USER }}"
